import type { Metadata } from "next";
import { PersonProvider } from "./lib/context/personContext";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body>
                <PersonProvider>
                    {children}
                </PersonProvider>

            </body>
        </html>
    );
}
